apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: prometheus-operated.default.svc.cluster.local:9090
  editable: true 

- name: Loki
  type: loki
  access: proxy
  url: loki.default.svc.cluster.local:3100
  editable: true
