{
 "title": "KubeVirt VMIs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kubevirt_vmi_memory_resident_bytes, node)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubevirt_vmi_memory_resident_bytes{node=~\"$node\"}, namespace)"
   },
   {
    "name": "vmi",
    "label": "vmi",
    "query": "label_values(kubevirt_vmi_memory_resident_bytes{node=~\"$node\", namespace=~\"$namespace\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Memory ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domain Resident Set Size (RSS)",
   "type": "graph",
   "description": "RSS of the process running the domain.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_resident_bytes{namespace=~\"$namespace\", name=~\"$vmi\", node=~\"$node\"}",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "description": "The total amount of available memory per VMI",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_available_bytes{namespace=~\"$namespace\", name=~\"$vmi\", node=~\"$node\"}",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Unused Memory",
   "type": "graph",
   "description": "The total amount of unused memory per VMI",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_unused_bytes{namespace=~\"$namespace\", name=~\"$vmi\", node=~\"$node\"}",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Swap traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_memory_swap_traffic_bytes_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"in\"}[5m])",
     "legendFormat": "in - {{namespace}}/{{name}}"
    },
    {
     "expr": "0 - rate(kubevirt_vmi_memory_swap_traffic_bytes_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"out\"}[5m])",
     "legendFormat": "out - {{namespace}}/{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_network_traffic_bytes_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"rx\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    },
    {
     "expr": "0 - rate(kubevirt_vmi_network_traffic_bytes_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"tx\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Traffic packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_network_traffic_packets_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"rx\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    },
    {
     "expr": "0 - rate(kubevirt_vmi_network_traffic_packets_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"tx\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Traffic errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_network_errors_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"rx\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    },
    {
     "expr": "0 - rate(kubevirt_vmi_network_errors_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"tx\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_storage_traffic_bytes_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"write\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    },
    {
     "expr": "rate(kubevirt_vmi_storage_traffic_bytes_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"read\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_storage_iops_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"write\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    },
    {
     "expr": "rate(kubevirt_vmi_storage_iops_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"read\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Time spent on operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_storage_times_ms_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"write\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    },
    {
     "expr": "rate(kubevirt_vmi_storage_times_ms_total{node=~\"$node\", namespace=~\"$namespace\", name=~\"$vmi\", type=\"read\"}[5m])",
     "legendFormat": "{{type}} - {{namespace}}/{{name}}"
    }
   ]
  }
 ]
}